general {
        colors = true
        interval = 5
        output_format = i3bar
}

order += "external mpdstatus"
order += "disk /"
order += "external kernel"

external mpdstatus {
		command = "mpc --host mpd.0pointer.org current"
		format = ". %status"
}

external kernel {
		command = "uname -r -o"
		format = ". %status"
}

disk "/" {
        format = ". %used / %total (%percentage_used)"
        prefix_type = "decimal"
}
